# Generated by Django 3.1.5 on 2021-08-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210821_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'compte', 'verbose_name_plural': 'comptes'},
        ),
        migrations.AlterField(
            model_name='account',
            name='is_cook',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cuisinier ?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_delivery_man',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Livreur ?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
