# Generated by Django 3.1.5 on 2021-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catégorie', 'verbose_name_plural': 'catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
