# Generated by Django 3.1.5 on 2021-08-21 22:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210821_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_image',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_default_image),
        ),
    ]
