# Generated by Django 3.1.5 on 2021-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.SmallIntegerField(default=1, editable=False),
        ),
    ]
