# Generated by Django 3.1.5 on 2021-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210827_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
